language: php

php:
  - '7.3'
  - '7.4'
  - '8.0'
  - nightly

jobs:
  allow_failures:
    - php: nightly

before_script: if [[ "$TRAVIS_PHP_VERSION" == '8.0' ]]; then composer require php-coveralls/php-coveralls -n ; fi

script:
  - phpunit
#  - if [[ "$TRAVIS_PHP_VERSION" == '8.0' ]]; then mkdir -p build/logs && phpunit --coverage-clover build/logs/clover.xml ; fi
#  - if [[ "$TRAVIS_PHP_VERSION" != '8.0' ]]; then phpunit ; fi

#after_script: if [[ "$TRAVIS_PHP_VERSION" == '8.0' ]]; then php vendor/bin/coveralls -v ; fi
