language: php

script: |
    if [[ $TRAVIS_PHP_VERSION = 7.* || $TRAVIS_PHP_VERSION = nightly ]]; then
        SYMFONY_PHPUNIT_VERSION=6.1 ./vendor/bin/simple-phpunit
    else
        ./vendor/bin/simple-phpunit
    fi
