sudo: false

language: php

php:
  - '7.1'
  - nightly
  
before_script: composer require satooshi/php-coveralls:^0.7

script:
  - mkdir -p build/logs && phpunit --coverage-clover build/logs/clover.xml
  - phpunit --coverage-text

after_script: php vendor/bin/coveralls -v
